FROM python:3.12

# set environment for debugging
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /dockerdjangosetup

COPY requirements.txt /dockerdjangosetup/

RUN pip install -r requirements.txt

COPY . /dockerdjangosetup/
